version: '3'
services:
  frontend:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-frontend:0.1
    deploy:
      replicas: 1
    ports:
      - "80:80"
    networks:
      - frontend

  mongo:
    image: mongo:3.6.3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - mongo-data:/data/db
    networks: 
      - backend

  eval:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-eval:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: EVAL:*
      DATA_VOLUME_NAME: hogwarts_eval-data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - eval-data:/data
    networks:
      - backend
      
  auth:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-auth:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: AUTH:*
      SERVER_MONGO: mongo
    networks:
      - backend
    
  course:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-course:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: COURSE:*
      SERVER_MONGO: mongo
    networks:
      - backend
  
  job:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-job:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: JOB:*
      SERVER_MONGO: mongo
      SERVER_COURSE: course
      SERVER_EVAL: eval
    networks:
      - backend
    
  gateway:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-gateway:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: GATEWAY:*
      SERVER_AUTH: auth
      SERVER_COURSE: course
      SERVER_JOB: job
    ports:
      - "8888:80"
    networks:
      - backend

  portainer:
    image: portainer/portainer
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    command: ["--admin-password-file", "/run/secrets/portainer-pass", "-H", "unix:///var/run/docker.sock"]
    secrets:
      - portainer-pass
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - backend
      - frontend
  
networks:
  backend:
  frontend:

volumes:
  portainer-data:
  eval-data:
  mongo-data: