version: '3'
services:
  kitchen:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-kitchen:0.1
    deploy:
      replicas: 1
    ports:
      - "88:8080"
    networks:
      - frontend
  
  hall:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-hall:0.1
    deploy:
      replicas: 1
    ports:
      - "80:8080"
    networks:
      - frontend

  mongo:
    image: mongo:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - mongo-data:/data/db
    networks: 
      - backend

  eval:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-eval:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: EVAL:*
      DATA_VOLUME_NAME: hogwarts_eval-data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - eval-data:/data
    networks:
      - backend
      
  auth:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-auth:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: AUTH:*
      SERVER_MONGO: mongo
    networks:
      - backend
    
  course:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-course:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: COURSE:*
      SERVER_MONGO: mongo
    networks:
      - backend
  
  job:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-job:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: JOB:*
      SERVER_MONGO: mongo
      SERVER_COURSE: course
      SERVER_EVAL: eval
    networks:
      - backend
    
  gateway:
    image: registry.cn-hongkong.aliyuncs.com/step8step/hogwarts-gateway:0.1
    deploy:
      replicas: 1
    environment:
      DEBUG: GATEWAY:*
      SERVER_AUTH: auth
      SERVER_COURSE: course
      SERVER_JOB: job
    ports:
      - "8888:80"
    networks:
      - backend
  
networks:
  backend:
  frontend:

volumes:
  eval-data:
  mongo-data: