swagger: '2.0'
info:
  version: "1.0.0"
  title: Hogwarts (Tech v2) API 文档（Eval）
  description: Hogwarts server-end api docs.
host: localhost:8082
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
security:
  - bearer_token: []
  - x_uid: []
paths:
  /eval/{jobid}:
    post:
      description: 评测一个作业
      parameters:
        - name: jobid
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              jobid:
                type: string
              result:
                type: string

securityDefinitions:
  bearer_token:
    description: | 
      设置访问令牌格式："Bearer token"（不包括双引号）。
      例如，`Bearer 1234` 。
      该值会做为请求头Authorization的值发送。
    type: apiKey
    name: Authorization
    in: header
  x_uid:
    description: | 
      在开发测试时，直接访问服务（即不通过代理`gate`访问）则不需要提供token，需要鉴权的API需要提供x-uid做为当前用户Id.
      该值会做为请求头x-uid的值发送。
    type: apiKey
    name: x-uid
    in: header