swagger: '2.0'
info:
  version: "1.0.0"
  title: Hogwarts (Tech v2) API 文档（Dbm）
  description: Hogwarts server-end api docs.
host: localhost:8004
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
security:
  - x_uid: []
paths:
  /db/mysql/{jobid}:
    post:
      description: 获取一个mysql数据库信息
      parameters:
        - name: jobid
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              jobid:
                type: string
              host:
                type: string
              port:
                type: string
              db:
                type: string
              user:
                type: string
              passwd:
                type: string
              
securityDefinitions:
  x_uid:
    description: | 
      在开发测试时，直接访问服务（即不通过代理`gate`访问）则不需要提供token，需要鉴权的API需要提供x-uid做为当前用户Id.
      该值会做为请求头x-uid的值发送。
    type: apiKey
    name: x-uid
    in: header