swagger: '2.0'
info:
  version: "1.0.0"
  title: Hogwarts (Tech v2) API 文档(Job)
  description: Hogwarts server-end api docs.
host: localhost:8002
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
security:
  - bearer_token: []
  - x_uid: []
paths:
  /jobs/{jobId}/file:
    get:
      description: 获取一个文件内容
      parameters:
        - name: jobId
          in: path
          type: string
          required: true
        - name: file
          description: 文件名，ex. path/to/readme.md
          in: query
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              file:
                type: string
              content:
                type: string
              job_id:
                type: integer
              hash:
                type: string
    post:
      description: 创建文件或更新已存在文件
      parameters:
        - name: jobId
          in: path
          type: string
          required: true
        - name: file
          description: 文件名
          in: body
          schema:
            type: object
            properties:
              name:
                description: 文件名
                type: string
              content:
                description: 文件内容
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              file:
                type: string
              job_id:
                type: string
              hash:
                type: string

  /jobs/{courseId}:
    get:
      description: 获取用户一个课程的所有作业信息
      parameters:
        - name: courseId
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/job'
  /jobs/{courseId}/{chapterId}/{sectionId}:
    get:
      description: 获取用户一个小节的作业
      parameters:
        - name: courseId
          in: path
          type: string
          required: true
        - name: chapterId
          in: path
          required: true
          type: string
        - name: sectionId
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              job:
                $ref: '#/definitions/job'
              files:
                type: array
                items:
                  description: 文件名
                  type: string
  /jobs/{jobId}/status/{status}:
    get:
      description: 修改一个作业的状态
      parameters:
        - name: jobId
          in: path
          type: integer
          required: true
        - name: status
          in: path
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              job:
                $ref: '#/definitions/job'

securityDefinitions:
  bearer_token:
    description: | 
      设置访问令牌格式："Bearer token"（不包括双引号）。
      例如，`Bearer 1234` 。
      该值会做为请求头Authorization的值发送。
    type: apiKey
    name: Authorization
    in: header
  x_uid:
    description: | 
      在开发测试时，直接访问服务（即不通过代理`gate`访问）则不需要提供token，需要鉴权的API需要提供x-uid做为当前用户Id.
      该值会做为请求头x-uid的值发送。
    type: apiKey
    name: x-uid
    in: header
    
definitions:
  job:
    type: object
    properties:
      id:
        type: integer
      uid:
        type: integer
      course_id:
        type: string
      chapter_id:
        type: string
      section_id:
        type: string
      status:
        type: string
      version:
        type: string
