version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: kissme
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks: 
      - backend

  eval:
    build: ./eval
    environment:
      DEBUG: EVAL:*
      DATA_VOLUME_NAME: server_eval-data
    command: npm start
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./eval:/app
      - eval-data:/data
    networks:
      - backend
      
  auth:
    build: ./auth
    environment:
      DEBUG: AUTH:*
      SERVER_MONGO: mongo
    command: npm start
    volumes:
      - ./auth:/app
    networks:
      - backend
    
  course:
    build: ./course
    environment:
      DEBUG: COURSE:*
      SERVER_MONGO: mongo
    command: npm start
    volumes:
      - ./course:/app
    networks:
      - backend
  
  job:
    build: ./job    
    environment:
      DEBUG: JOB:*
      SERVER_MONGO: mongo
      SERVER_COURSE: course
      SERVER_EVAL: eval
    command: npm start
    volumes:
      - ./job:/app
    networks:
      - backend
    
  gateway:
    build: ./gateway 
    environment:
      DEBUG: GATEWAY:*
      SERVER_AUTH: auth
      SERVER_COURSE: course
      SERVER_JOB: job
    command: npm start
    volumes:
      - ./gateway:/app
    ports:
      - "8888:80"
    networks:
      - backend
  
networks:
  backend:

volumes:
  eval-data:
  mongo-data:
  mysql-data: